import polars as pl
import requests
import json

GROUND_TRUTH_SCHEMA = {
    "year", "week", "season", "player_id", "player_name", "team", "position",
    "games_played", "fpts", "fpts_ppr", "fpts_per_game", "fpts_ppr_per_game",
    "yds", "td", "targets", "rec",
    "opponent", "stadium_name", "city", "state", "indoor_outdoor", "surface_type",
    "elevation", "game_result"
}

def validate_consistency():
    print("Beginning E2E Validation...")
    
    # 1. Validate Parquet Source
    df = pl.read_parquet("data/official_rankings/position/WR_weekly.parquet")
    parquet_schema = set(df.columns)
    missing_in_etl = GROUND_TRUTH_SCHEMA - parquet_schema
    assert not missing_in_etl, f"ETL silently dropped columns: {missing_in_etl}"
    print("[OK] ETL Schema matches Ground Truth")

    # 2. Validate Backend API Response
    response = requests.get("http://localhost:8000/api/v1/weekly-rankings?position=wr&year=2024&week=1&limit=1")
    response.raise_for_status()
    api_payload = response.json()
    
    if not api_payload:
        print("[SKIP] No API data to validate.")
        return
        
    api_schema = set(api_payload[0].keys()) - {"rank"} # Rank is dynamically generated by API
    missing_in_api = GROUND_TRUTH_SCHEMA - api_schema
    assert not missing_in_api, f"Backend API dropped columns: {missing_in_api}"
    print("[OK] Backend API serves complete payload schema")
    
    print("SUCCESS: Zero silent data loss detected.")

if __name__ == "__main__":
    validate_consistency()
